### ISSUE TITLE
Make sure that all of our models are linkable. 

### ISSUE THREAD

**Issue by collinc777** [collinc777/idb#10]
So abut this one....
We need to test the apis we are using and make sure that they actually have enough data in it to fulfill our needs.  Their schemes are right for us but if they don't have any data to fill those schemes then things will get challenging and we will probably need to pivot on ideas. This needs to be done ASAP!

**Comment by ibly31UT** [comment]
I'll manually grab data (without using the APIs quite yet) for the 3 instances for each model, and ensure that they are linkable. This is a prerequisite for the other issue I self-assigned of making the static pages for each of the models. I'm sure that even if both APIs don't provide enough information, we can create linkabilities between our model types.

**Comment by gregorymcdonald** [comment]
Checked this, all models can be linked with another model in some meaningful way.
