### ISSUE TITLE
Create a set of unit tests of the models.

### ISSUE THREAD

**Issue by collinc777** [collinc777/idb#13]
Create a set of unit tests of the models.
They can't be run, yet.

**Comment by BrianZhu1** [comment]
Is this for the UML or unit tests? I think this is referring to the unit tests (created a separate issue for UML)

**Comment by gregorymcdonald** [comment]
This is for unit tests. We have over 10 now so I'll close this. We'll need to update our current tests once we integrate with SQLAlchemy.

**Comment by gregorymcdonald** [comment]
Unit tests need to be updated to match format described in Piazza post @278.
