### ISSUE TITLE
Document a RESTful API using Apiary

### ISSUE THREAD

**Issue by BrianZhu1** [collinc777/idb#19]

**Comment by BrianZhu1** [comment]
Not sure if we have the documentation yet (can someone confirm?)

**Comment by collinc777** [comment]
I just connected it to apiary. No documentation yet.

**Comment by BrianZhu1** [comment]
Can you invite the other team members to the project? To do it, go to Apiary, click on the "people" icon at the top, and enter the email addresses

**Comment by collinc777** [comment]
Done
