### ISSUE TITLE
Link AWS instance to the purchased domain name. gotthrones.me

### ISSUE THREAD

**Issue by collinc777** [collinc777/idb#3]

**Comment by gregorymcdonald** [comment]
Here's an article I found (don't know how helpful it is): [Article](http://techgenix.com/namecheap-aws-ec2-linux/)

**Comment by gregorymcdonald** [comment]
I own the namecheap account linked to our domain so let me know what I need to do on that end to get it connected.

**Comment by collinc777** [comment]
just need the credenials for this and we'll be good to test it
