### ISSUE TITLE
Create presentation

### ISSUE THREAD

**Issue by ibly31UT** [collinc777/idb#57]

**Comment by gregorymcdonald** [comment]
Google Slides link: https://docs.google.com/presentation/d/19NSpy8TCvVkxPznFF9e2qI-CEqy1yf2A_ciCfaF0Bcs/edit?usp=sharing

**Comment by gregorymcdonald** [comment]
Create a presentation.
Use any software that you like (e.g. Keynote, Powerpoint, Prezi, Slides).
Include the critiques above.

Give a 15 min presentation in class.
Include the following:
Group members
Demonstration
Critiques above
