### ISSUE TITLE
Define our models 

### ISSUE THREAD

**Issue by collinc777** [collinc777/idb#8]

**Comment by gregorymcdonald** [comment]
Models for Book, Character, and House have been defined. Currently blocked until the fourth model is decided upon.

**Comment by gregorymcdonald** [comment]
Fourth model is: "Okay, sat with Adam for a bit after class and brainstormed on what 4th model we should have. The only viable one we can really do is Alliances. Alliances have the following 5 attributes: Head leader (currentLord of the overlord), Military strength by number of sworn characters, Military strength by number of ancestral weapons it has access to, Military strength by number of "seats" it has access to (basically castles/major cities it controls), Regions it encompasses, and Cultures it encompasses. Then the two models it can point to are characters and houses."
And has now been defined in models.py
