### ISSUE TITLE
Create a set of static html pages for all of our models. 

### ISSUE THREAD

**Issue by collinc777** [collinc777/idb#9]

**Comment by ibly31UT** [comment]
Not sure yet if I'll implement this with a listing style page (eg. /characters) that leads to an individual informational page (/characters/2) that displays the full detailed information. Or if I can get away with just making the /characters listing page display all the attributes, including embedded media, in a nice gridlike layout that does 3 side-by-side, and collapses to 3 rows when the screen size is mobile.

**Comment by gregorymcdonald** [comment]
We need to make all of our model pages into grids instead of tables. RIP
